<?php
namespace mychaelstyle\fops;

use \mychaelstyle\fops\OpsShow;
use \mychaelstyle\photo\Photo;
use \mychaelstyle\fops\PrinterStdOut;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.1 on 2013-08-21 at 00:16:00.
 */
class FolderTest extends \PHPUnit_Framework_TestCase
{
  /**
   * @var Folder
   */
  protected $object;

  /**
   * Sets up the fixture, for example, opens a network connection.
   * This method is called before a test is executed.
   */
  protected function setUp()
  {
    parent::setUp();
    $this->object = new Folder('/Users/masanori/Pictures');
  }

  /**
   * Tears down the fixture, for example, closes a network connection.
   * This method is called after a test is executed.
   */
  protected function tearDown()
  {
    parent::tearDown();
  }

  /**
   * @covers mychaelstyle\fops\Folder::addOps
   */
  public function testAddOps()
  {
    $ops = new OpsShow();
    $this->object->addOps($ops);
  }

  /**
   * @covers mychaelstyle\fops\Folder::addPrinter
   */
  public function testAddPrinter()
  {
    $printer = new PrinterStdOut();
    $this->object->addPrinter($printer);
  }

  /**
   * @covers mychaelstyle\fops\Folder::operate
   * @covers mychaelstyle\fops\Folder::scan
   * @covers mychaelstyle\fops\Folder::ooops
   */
  public function testOperate()
  {
    $ops = new Photo();
    //$ops = new OpsShow();
    $this->object->addOps($ops);
    $printer = new PrinterStdOut();
    $this->object->addPrinter($printer);
    $this->object->operate();
  }
}
